# Generated by Django 5.1.7 on 2025-10-27 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('job_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('folder_name', models.CharField(default='Word_Files', max_length=255)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'job_records',
                'indexes': [models.Index(fields=['is_active'], name='job_records_is_acti_b6deea_idx'), models.Index(fields=['created_at'], name='job_records_created_27f1be_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=100)),
                ('folder_name', models.CharField(default='Word_Files', max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('conversion_complete', models.BooleanField(default=False)),
                ('download_complete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'uploaded_files',
                'indexes': [models.Index(fields=['job_id'], name='uploaded_fi_job_id_e641a2_idx'), models.Index(fields=['download_complete'], name='uploaded_fi_downloa_b6741a_idx')],
            },
        ),
    ]
