# Generated by Django 5.1.7 on 2025-10-27 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_jobrecord_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('subcategory_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'excel_mappings',
                'indexes': [models.Index(fields=['job_id'], name='excel_mappi_job_id_813129_idx'), models.Index(fields=['title'], name='excel_mappi_title_56b3db_idx')],
            },
        ),
    ]
