# Generated by Django 5.1.7 on 2025-10-27 06:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_excelmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractExcelData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=100)),
                ('row_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'extract_excel_data',
                'indexes': [models.Index(fields=['job_id'], name='extract_exc_job_id_fd1e4e_idx')],
            },
        ),
    ]
